apiVersion: v1
kind: Namespace
metadata:
  name: batch55

--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: batch55
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  


  ####